const regionList = [
    { area: "上海省" },
    { area: "河北省" },
    { area: "山西省" },
    { area: "内蒙古省" },
    { area: "辽宁省" },
    { area: "吉林省" },
    { area: "黑龙江省" },
    { area: "江苏省" },
    { area: "浙江省" },
    { area: "安徽省" },
    { area: "福建省" },
    { area: "江西省" },
    { area: "山东省" },
    { area: "河南省" },
    { area: "湖北省" },
    { area: "湖南省" },
    { area: "广东省" },
    { area: "广西省" },
    { area: "海南省" },
    { area: "四川省" },
    { area: "贵州省" },
    { area: "云南省" },
    { area: "西藏省" },
    { area: "陕西省" },
    { area: "甘肃省" },
    { area: "青海省" },
    { area: "宁夏省" },
    { area: "新疆省" },
    { area: "北京省" },
    { area: "天津省" },
    { area: "重庆省" },
    { area: "香港省" },
    { area: "澳门省" },
    { area: "海外" },
]
export {
    regionList
};